# Python numpy

In [3]:
'''
Lo primero es comprobar que tenemos instalado nmumpy y que lo podemos importar correctamente.
La ejecución de este bloque de código nos debe mostrar el array [1,2,3,4,5]
'''
import numpy as np

# Definición de un nuevo 'ndarray', de ahora en adelante lo llamaremos simplemente 'array'
test = np.array([1, 2, 3, 4, 5])
print(test)


ModuleNotFoundError: No module named 'numpy'

### Primeros pasos

In [4]:
# Para inicar un array de nunpy llamamos al a funcion np.array()
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [6]:
# Para inicializar un array de dim 2 podemos pasar una lista de listas
b = np.array( [[1, 2, 3], [4, 5, 6]]  )
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Podemos anidar mas listas para crear arrays de dim 3 o mas
c = np.array( [
    [
        [1, 2, 3], [4, 5, 6]
    ],
    [
        [1, 2, 3], [4, 5, 6]
    ]
    ] )
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [9]:
# Obtener la dimensión de un array
a.ndim

1

In [10]:
'''
Obeter la dimension del array b
'''
b.ndim

2

In [25]:
'''
Obtener la dimension del array c
'''
c.ndim

3

In [18]:
# vamos a crea un array de 3 dimensiones
d = np.array(
    [[[1,4,7],[2,9,7],[1,3,0],[9,6,9]],
    [[2,3,4],[4,5,5], [1,2,2],[9,3,8]]]
)
print(d)
print(d.ndim)

[[[1 4 7]
  [2 9 7]
  [1 3 0]
  [9 6 9]]

 [[2 3 4]
  [4 5 5]
  [1 2 2]
  [9 3 8]]]
3


In [21]:
# El shape de un array es una tupla que indica el tamaño de cada dimensión
print(a)
print(a.shape)

[1 2 3 4 5]
(5,)


In [22]:
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [24]:
print(c)
print(c.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [27]:
print(d)
print(d.shape)

[[[1 4 7]
  [2 9 7]
  [1 3 0]
  [9 6 9]]

 [[2 3 4]
  [4 5 5]
  [1 2 2]
  [9 3 8]]]
(2, 4, 3)


In [28]:
# Obtener el tipo de dato de un array
a.dtype

dtype('int64')

In [29]:
# Representación de un byte en binario -> 1010

# El tipo int16 puede representar un número entero de 16 bits (2 bytes)(-32.768 a 32.767)
# El tipo int32 puede representar un número entero de 32 bits (4 bytes)(-2.147.483.648 a 2.147.483.647)
# El tipo int64 puede representar un número entero de 64 bits (8 bytes)(-9.223.372.036.854.775.808 a 92.23.372.036.854.775.807)

#El tipo float32 puede representar un número real de 32 bits (4 bytes)(-3.4028235e+38 a 3.4028235e+38)
#El tipo float64 puede representar un número real de 64 bits (8 bytes)(-1.7976931348623157e+308 a 1.7976931348623157e+308)

In [31]:
''' 
Define un array de dim 2 y de tipo int16
'''
a16 = np.array([[1,2,3],[4,5,6]], dtype=np.int16)
print(a16)
print(a16.dtype)

[[1 2 3]
 [4 5 6]]
int16


In [34]:
# El  tipo de dato no es capaz de manejar valores fuera de su rango (32.768) por lo que se produce un overflow 
# e introduce basura
b16 = np.array([[1,2,3],[4,5,64000]], dtype=np.int16)
print(b16)

[[    1     2     3]
 [    4     5 64000]]


In [40]:
# Redefinir el tipo de un array
'''
convertir el array a16 a tipo int32
'''
a32 = a16.astype(np.int32)
print(a16.dtype)
print(a16)
print(a32.dtype)
print(a32)

int16
[[1 2 3]
 [4 5 6]]
int32
[[1 2 3]
 [4 5 6]]


In [50]:
# Saber cuanto ocupa en memoria un array
# utilizando el array de ejemplo anterior a16
'''
obterner cuanto ocupa en memoria un elemento del array a16
'''
print("Array a16\n",a16)
print("")

# numero de elemento que tiene el array
print('Elementos array a16:', a16.size)
print('Tamaño de cada elemento del array a16:', a16.itemsize, 'bytes')
print('Tamaño total del array a16:', a16.size * a16.itemsize, 'bytes')


Array a16
 [[1 2 3]
 [4 5 6]]

Elementos array a16: 6
Tamaño de cada elemento del array a16: 2 bytes
Tamaño total del array a16: 12 bytes


In [51]:
# Saber cuanto ocupa en memoria un array
# utilizando el array de ejemplo anterior a32
'''
obterner cuanto ocupa en memoria un elemento del array a32
'''
print("Array a32\n",a32)
print("")

# numero de elemento que tiene el array
print('Elementos array a32:', a32.size)
print('Tamaño de cada elemento del array a32:', a32.itemsize, 'bytes')
print('Tamaño total del array a32:', a32.size * a32.itemsize, 'bytes')

Array a32
 [[1 2 3]
 [4 5 6]]

Elementos array a32: 6
Tamaño de cada elemento del array a32: 4 bytes
Tamaño total del array a32: 24 bytes


In [61]:
# Otra forma de inicializar un array (range)
# Ejemplo de rage
ejemplo1 = list(range(10, 20, 2))
print(ejemplo1)

# for i in range(10):
#     print(i)

[10, 12, 14, 16, 18]


In [57]:
'''
inicializar array con range. El array debe tener 10 elementos
'''
a = np.array(range(10))
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
'''
Inicializa un array con arange. El array debe tener 10 elementos
'''
b = np.arange(10)
print(b)


[0 1 2 3 4 5 6 7 8 9]


In [64]:
'''
Inicializa un array con arange. desde 10 hasta 20 con paso 2
'''
c = np.arange(10,20,2)
print(c)

[10 12 14 16 18]


Ejercicios

In [68]:
'''
Define el array 'a' del 1 al 10
'''
a = np.arange(1,11)
print(a)
'''
Imprime la dimension del array y el shape
'''
print(a.ndim)
print(a.shape)



[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)


In [71]:
''' 
Define de un array 'b' de dimensiones 2x3 a partir de listas anidadas
'''
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [73]:
'''
Define un array 'c'  de dim 2x2x3 a partir de una lista de listas anidadas 
'''

c = np.array([
    [[1,2,3],[4,5,6]]
    ,[[7,8,9],[10,11,12]]
    ])

'''
Imprime el número total de elementos del array y el shape
'''
print(c.size)
print(c.shape)

12
(2, 2, 3)


## Accediendo y Modificando elementos de un array

In [76]:
# Array de 2x5
f = np.array([[1,2,3,8,7],[4,5,6,2,9]])
print(f)

[[1 2 3 8 7]
 [4 5 6 2 9]]


Obtener un elemento de un array

In [79]:
# Obtener un elemento concreto de un array [rows,columns]
# obtener el elemento 6 del array f
print(f[1,2])

# Obtener el elemento 8 del array f
print(f[0,3])

6
8


Obtener una fila completa de un array

In [82]:
# Para obtener una fila completa utilizamos la notación ':' como en la listas
print(f)
f[1,:]

[[1 2 3 8 7]
 [4 5 6 2 9]]


array([4, 5, 6, 2, 9])

Obtener una columna completa de un array

In [86]:
# define un array 'f' de dimensiones 4x5
# Obtener la columna 3 de array f
f = np.array([[1,2,3,8,7],[4,5,6,2,9],[1,2,3,8,7],[4,5,6,2,9]])
print(f)
f[:,2]

[[1 2 3 8 7]
 [4 5 6 2 9]
 [1 2 3 8 7]
 [4 5 6 2 9]]


array([3, 6, 3, 6])

Otras formas de acceder a los elementos de un array

In [88]:
# Para acceder de una forma un poco más avanzada se utiliza [inicio: final: paso]
f[0,1:4:2]

array([2, 8])

In [89]:
# Obtener la filas pares
f[::2,:]


array([[1, 2, 3, 8, 7],
       [1, 2, 3, 8, 7]])

In [92]:
# Recorrer el array con paso negativo
f_invertido = f[::-1,:] # Invertir el array
print(f_invertido)

[[4 5 6 2 9]
 [1 2 3 8 7]
 [4 5 6 2 9]
 [1 2 3 8 7]]


In [17]:
# Definir un array de 3x3x2
g = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])
print(g)
g.shape

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


(3, 3, 2)

Actualizar un elemento de un array

In [105]:
# Podemos actualizar la información de un array igual que seleccionando un elemento e igulandolo con un nuevo valor
h = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]])

print(h)
print()

# establecer el elemento 50 a 500
h[1,1,1] = 500
print(h)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 40 500  60]
  [ 70  80  90]]]


In [110]:
# Podemos actulizar una fila completa
i = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]])
print(i)
print()

# Establecer la fila 0 del elemento 1 a 0
i[1,0,:] = 0
print(i)
print()

# Establecer la fila 0 del elemento 1 a 1,2,3
i[1,0,:] = [1,2,3]
print(i)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 0  0  0]
  [40 50 60]
  [70 80 90]]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1  2  3]
  [40 50 60]
  [70 80 90]]]


In [113]:
# Definir un array de 3x3x2
j = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]])
print(j)
print()
# Establecer la ultima columna de todos los elementos a 0
j[:,:,-1] = 0
print(j)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

[[[ 1  2  0]
  [ 4  5  0]
  [ 7  8  0]]

 [[10 20  0]
  [40 50  0]
  [70 80  0]]]


In [114]:
# Definir un array de 3x3x2
k = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]])
print(k)
print()
# Establecer la ultima columna de todos los elementos a [ 1, 2, 3]
k[:,:,-1] = [1,2,3]
print(k)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

[[[ 1  2  1]
  [ 4  5  2]
  [ 7  8  3]]

 [[10 20  1]
  [40 50  2]
  [70 80  3]]]


Ejercicios

In [ ]:
'''
Define un array 's' de tamaño 10 y selecciona el valor de la posición 5
'''

In [ ]:
'''
Sobre el array s, selecciona el valor 5
'''

In [ ]:
'''
Define el array 's' de tamaño 25 y selecciona los valores pares
'''

In [ ]:
'''
Define el array 's' de tamaño 25 y selecciona los valores impares
'''

In [ ]:
'''
Sobre el array s, selecciona el uĺltimo valor
'''

In [ ]:
"""
Define el array 's' de tamaño 20 e invierte el orden de los valores
"""

In [ ]:
'''
Define un array s2 multidimensional de tamaño 2x2 y selecciona el valor de la segunda fila y la segunda columna
'''

In [ ]:
'''
Define el array:
[
[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
]
y selecciona el valor de la segunda dimension, primera fila, segunda columna
'''

In [ ]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a 99
'''

In [ ]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a (0,1), (2,3), (4,5), (6,7)
'''

## Inicializando diferentes tipos de arrays

Matriz de ceros

In [115]:
# Definir una matriz completa de 0 de tamaño 5x3
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [116]:
# Definir una matriz completa de 0 de tipo int32 de tamaño 5x3
np.zeros((5,3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [137]:
# Podemos genera una matriz de zeros con un shape (2,3,4)
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [122]:
# Definir una matriz de tamaño 5x3
l = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(l)
print(l.dtype)
# Definir una matriz de 0 del shape de l
zeros1 = np.zeros(l.shape)
print(zeros1)
print(zeros1.dtype)
# Otra forma de hacerlo es con la función 'zeros_like' Esta respeta el tipo de dato de la matriz original
print(np.zeros_like(l))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
int64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


Matriz de unos

In [123]:
# Define una matriz de 1 de tamaño 5x3
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [124]:
# Define una matriz de 1 de tamaño 5x3 de tipo int32
np.ones((5,3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

Matriz de valores concretos

In [125]:
# Define una matriz de tamaño 5x3 con valores = 50
np.full((5,3), 50)

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [132]:
# Define una matriz de tamaño 5x3 con valores = 50 en punto flotante
p = np.full((5,3), 50.) # Si ponemos el punto detras del valor, python infiere que queremo un float

Matriz de valores concretos (full like)

In [133]:
# define una matriz como p (la matriz anterior) pero con valores = 75
np.full_like(p, 75)

array([[75., 75., 75.],
       [75., 75., 75.],
       [75., 75., 75.],
       [75., 75., 75.],
       [75., 75., 75.]])

Matriz de números aleatorios

In [134]:
# Atención!! Cuando creamos una matriz de números aleatorios NO se pasa 
# el shape por parametro como hemos hecho con los ceros o los ones

# Define una matriz de tamaño 5x3 con valores aleatorios
np.random.rand(5,3)

array([[0.28971795, 0.36105046, 0.46586415],
       [0.69884083, 0.05991784, 0.60148804],
       [0.78676116, 0.34900249, 0.07938793],
       [0.82145921, 0.09404639, 0.32131281],
       [0.80572275, 0.6487967 , 0.24160158]])

In [144]:
# Definir una matriz de 5x3 con valore comprendidos entre 0 y 100
np.random.randint(0,100,size=(5,3))

array([[65, 32, 88],
       [17, 45, 37],
       [72, 61, 98],
       [98,  9, 89],
       [26, 16, 62]])

In [148]:
# Definir una matriz de 5x3 con valore comprendidos entre 100 y 200
np.random.randint(100,200,size=(5,3))

array([[116, 117, 117],
       [129, 198, 101],
       [116, 138, 187],
       [186, 146, 118],
       [129, 190, 100]])

In [150]:
# Definir una matriz de 5x3 con valores alazares mayores que 1
np.random.rand(5,3) * 100

array([[ 5.00150782, 54.72835001, 65.20541996],
       [60.00654991, 69.29200709, 78.91472833],
       [77.60286809, 31.31636533, 29.05304361],
       [58.87140494, 48.22362112, 64.68401439],
       [80.70646164, 49.51362588, 80.78276457]])

Matriz identidad

In [191]:
# Define la matriz identidad de tamaño 5x5
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [190]:
# La matriz identidad se puede definir con la función 'identity'
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Ejercicios

In [ ]:
'''
Define el array z de dim 1 completo de ceros
'''


In [ ]:
'''
Define un array z de dim 8x8 completo de ceros
'''


In [ ]:
'''
Define el array 'z' completo de ceros de n dim
'''


In [ ]:
'''
Define el array 'd' completo de unos de n dim
'''


In [ ]:
'''
Define un array como el que se muestra a continuación:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
'''

In [ ]:
'''
Define un array 'g' conun range de 0 a 10 de dim 2
'''


In [ ]:
'''
Define un array 'h' con un range de 0 a 100 con un paso de 5 y una dim difrente de 1
'''


## Operaciones con arrays

operaciones básicas

In [153]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [154]:
# Suma
print(a + 2)

[3 4 5 6 7]


In [155]:
# Resta
print(a - 2)

[-1  0  1  2  3]


In [156]:
# Multiplicación
print(a * 2)

[ 2  4  6  8 10]


In [157]:
# División
print(a / 2)

[0.5 1.  1.5 2.  2.5]


In [158]:
# Exponenciacion
print(a ** 2)

[ 1  4  9 16 25]


In [160]:
# Las operaciones basicas con arrays o matrices son "elemet wise". Esto significa que se aplican a cada elemento de la matriz.

In [161]:
b = np.array([10, 20, 30, 40, 50])
print(b)

[10 20 30 40 50]


In [163]:
# Podemos sumar dos arrays porque son del mismo tamaño
print(a + b)

[11 22 33 44 55]


Ejercicios

In [174]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación suma los valores de ambos arrays y 
comprueba que los valores son correctos.
'''
a = np.random.randint(0,100,size=(4))
print(a)
b = np.ones((4))
print(b)
print(a + b)

[88 64  6 67]
[1. 1. 1. 1.]
[89. 65.  7. 68.]


In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. 
A contunuación resta los valores de ambos arrays y comprueba que los valores son correctos.
'''

In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 2s. A contunuación multiplica o divide los valores de ambos arrays y comprueba que los valores son correctos.
'''

Álgebra lineal

numpy py permite realizar operaciones matriciales como por elemplo:
- determinante: np.linalg.det()
- inversa: np.linalg.inv()
- producto matricial: np.dot()
- diagonal: np.diag()
- inversa de una matriz: np.linalg.inv()



In [176]:
# Definir una matriz de 2x3 con valores aleatorios entre 0 y 10
a = np.random.randint(0,10,size=(2,3))
print(a)

[[5 7 8]
 [0 3 3]]


In [179]:
# Definir una matriz de 3x2 con valores aleatorios entre 0 y 10
b = np.random.randint(0,10,size=(3,2))
print(b)

[[4 5]
 [8 4]
 [7 4]]


In [ ]:
# Esto va a dar error porque va a tratar de hacer la operación element wise
print(a*b)

In [182]:
# Para realizar la multiplicación matemática de matrices debemos usar la función 'dot' o 'matmul'
producto = np.dot(a,b)
print(producto)

[[132  85]
 [ 45  24]]


In [183]:
producto = np.matmul(a,b)
print(producto)

[[132  85]
 [ 45  24]]


In [186]:
producto = a @ b
print(producto)

[[132  85]
 [ 45  24]]


In [ ]:
# Ejemplo de error
c = np.random.randint(0,10,size=(3,2))
print(c)
print(np.dot(b,c))

In [194]:
# Obtener el determinante de una matriz
a = np.identity(3)
print(a)
print('Determinante;',np.linalg.det(a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinante; 1.0


In [195]:
# Define una matriz de 3x3 con valores aleatorios entre 0 y 10
b = np.random.randint(0,10,size=(3,3))
print(b)
# Obtener el determinante de la matriz
print('Determinante:',np.linalg.det(b))

[[2 4 6]
 [9 1 6]
 [6 2 5]]
Determinante: 22.000000000000014


In [198]:
# Matriz inversa
# La matriz inversa de una matriz es igual a la matriz adjunta de su matriz traspuesta, 
# dividida por su determinante, siempre que este no sea cero.

# Define una matriz de números aleatorios entre 0 y 10 de tamaño 3x3
c = np.random.randint(0,10,size=(3,3))
print(c)
# Obtener la matriz inversa
inversa = np.linalg.inv(c)
print('Matriz inversa:\n',inversa)

[[5 8 0]
 [2 9 3]
 [7 0 3]]
Matriz inversa:
 [[ 0.10588235 -0.09411765  0.09411765]
 [ 0.05882353  0.05882353 -0.05882353]
 [-0.24705882  0.21960784  0.11372549]]


In [199]:
# Matriz transpuesta
# La matriz transpuesta de una matriz es otra matriz que se obtiene al intercambiar las filas por las columnas.
d = np.random.randint(0,10,size=(3,5))
print(d)
# Obtener la matriz transpuesta
np.transpose(d)


[[9 6 2 6 4]
 [6 4 4 2 1]
 [2 3 6 6 1]]


array([[9, 6, 2],
       [6, 4, 3],
       [2, 4, 6],
       [6, 2, 6],
       [4, 1, 1]])

Más tipos de operaciones con arrays:
- **np.sum():** Suma de todos los elementos de un array
- **np.mean():** Media de todos los elementos de un array
- **np.std():** Desviación estándar de todos los elementos de un array
- **np.var():** Varianza de todos los elementos de un array
- **np.min():** Valor mínimo de todos los elementos de un array
- **np.max():** Valor máximo de todos los elementos de un array
- **np.argmin():** Indice del valor mínimo de un array
- **np.argmax():** Indice del valor máximo de un array
- **np.cumsum():** Sumatoria acumulada de un array
- **np.cumprod():** Producto acumulado de un array
- **np.flip():** Inversa de un array


In [201]:
# Define una matriz de números aleatorios entre 0 y 10 de tamaño 3x3
e = np.random.randint(0,10,size=(3,3))
print(e)

[[2 5 8]
 [3 7 4]
 [2 4 0]]


In [202]:
# Obtener el suma de todos los elementos de la matriz
print(np.sum(e))

35


In [203]:
# Obetener la media de todos los elementos de la matriz
print(np.mean(e))

3.888888888888889


In [204]:
# Obetener el valor máximo de una matriz
print(np.max(e))

8


In [205]:
# Obetener el valor mínimo de una matriz
print(np.min(e))

0


In [208]:
# Obtener el valor máximo de cada fila
print('máximo de cada fila:',np.max(e,axis=1))
# Obtener el valor máximo de cada columna
print('máximo de cada coluna:',np.max(e,axis=0))

máximo de cada fila: [8 7 4]
máximo de cada coluna: [3 7 8]


In [211]:
# Obtener el valor máximo de e[1:3,1:3]
print(e[1:3,1:3])
print(np.max(e[1:3,1:3]))

[[7 4]
 [4 0]]
7


In [213]:
# Obtener el sumatorio de cada fila
print('Sumatorio de cada fila:',np.sum(e,axis=1))
# Obtener el sumatorio de cada columna
print('Sumatorio de cada coluna:',np.sum(e,axis=0))

Sumatorio de cada fila: [15 14  6]
Sumatorio de cada coluna: [ 7 16 12]


Ejercicios

In [ ]:
import numpy as np

In [ ]:
'''
Calcula la mediana de un array
'''

In [ ]:
'''
calcula la media de una matriz
'''

### Reshape

In [219]:
matriz1 = np.array([[1, 2, 3], [4, 5, 6]])
matriz1

array([[1, 2, 3],
       [4, 5, 6]])

In [221]:
matriz2 = matriz1.reshape(3, 2)
matriz2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [223]:
matriz3 = matriz1.reshape(1, 6)
matriz3

array([[1, 2, 3, 4, 5, 6]])

In [226]:
# Ejemplo practico de reshape
z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(z)
print(z.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


In [230]:
# reshape a 2 dimensiones
z = z.reshape(4, 5)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [232]:
# reshape a 3 dimensiones
z.reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [45]:
# Crear un fichero
data = np.random.randint(0,100,size=(8,9), dtype=np.int32)
data

array([[ 9, 30, 65, 66, 42, 88, 72, 21, 50],
       [42,  9, 52, 60, 28, 98, 25, 83, 40],
       [79, 39,  8, 96, 71, 68, 56, 34, 40],
       [27,  6, 55,  6, 57, 81, 91, 57, 61],
       [51, 35, 81, 25, 84,  0, 59, 65, 28],
       [69,  0, 63, 35, 15, 44,  7, 46, 93],
       [70, 37, 84,  3, 15, 79, 74, 79, 61],
       [71, 78, 33, 44, 96, 22, 33, 25, 80]], dtype=int32)

In [48]:
# Guarda el array f en un csv
np.savetxt('file_data.csv', data, delimiter=';', fmt='%d')


In [50]:
# Carga el contenido del csv en un array llamado file_data
file_data = np.loadtxt('file_data.csv', delimiter=';', dtype=np.int32)
print(file_data)

[[ 9 30 65 66 42 88 72 21 50]
 [42  9 52 60 28 98 25 83 40]
 [79 39  8 96 71 68 56 34 40]
 [27  6 55  6 57 81 91 57 61]
 [51 35 81 25 84  0 59 65 28]
 [69  0 63 35 15 44  7 46 93]
 [70 37 84  3 15 79 74 79 61]
 [71 78 33 44 96 22 33 25 80]]


Máscaras Booleanas

In [51]:
print(file_data)

[[ 9 30 65 66 42 88 72 21 50]
 [42  9 52 60 28 98 25 83 40]
 [79 39  8 96 71 68 56 34 40]
 [27  6 55  6 57 81 91 57 61]
 [51 35 81 25 84  0 59 65 28]
 [69  0 63 35 15 44  7 46 93]
 [70 37 84  3 15 79 74 79 61]
 [71 78 33 44 96 22 33 25 80]]


In [52]:
# Podemos generar una máscara booleana para filtrar los datos
file_data > 75

array([[False, False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False,  True, False],
       [ True, False, False,  True, False, False, False, False, False],
       [False, False, False, False, False,  True,  True, False, False],
       [False, False,  True, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True],
       [False, False,  True, False, False,  True, False,  True, False],
       [False,  True, False, False,  True, False, False, False,  True]])

In [55]:
# Esta máscara se puede aplicar a cualquier array
resultado =  file_data[file_data > 75]
print(resultado)
resultado.shape

[88 98 83 79 96 81 91 81 84 93 84 79 79 78 96 80]


(16,)

In [66]:
# Generar una lista de edades aleatorias
edades = np.array([25,48,4,15,24,52])
# Personas
personas = np.array(['Juan', 'Ana', 'Pedro', 'Luis', 'María', 'Pablo'])
print(edades)
print(personas)

# mayores de 18 años
mayores_18 = edades > 18
print(mayores_18)

# Aplicar la máscara a la lista de personas
personas_mayores_18 = personas[mayores_18]
print(personas_mayores_18)

[25 48  4 15 24 52]
['Juan' 'Ana' 'Pedro' 'Luis' 'María' 'Pablo']
[ True  True False False  True  True]
['Juan' 'Ana' 'María' 'Pablo']


In [71]:
# También podemos ver si alguno de los elementos cumple una condición
print(file_data)
print(np.any(file_data > 75))

[[ 9 30 65 66 42 88 72 21 50]
 [42  9 52 60 28 98 25 83 40]
 [79 39  8 96 71 68 56 34 40]
 [27  6 55  6 57 81 91 57 61]
 [51 35 81 25 84  0 59 65 28]
 [69  0 63 35 15 44  7 46 93]
 [70 37 84  3 15 79 74 79 61]
 [71 78 33 44 96 22 33 25 80]]
True


In [75]:
# Any indicando el axis=0 (en las columnas)
# Devuleve un booleano de tamaño igual al número de columnas.
column_mayor_que_80 = np.any(file_data > 80, axis=0)
column_mayor_que_90 = np.any(file_data > 90, axis=0)

file_data[:,column_mayor_que_90]

array([[66, 42, 88, 72, 50],
       [60, 28, 98, 25, 40],
       [96, 71, 68, 56, 40],
       [ 6, 57, 81, 91, 61],
       [25, 84,  0, 59, 28],
       [35, 15, 44,  7, 93],
       [ 3, 15, 79, 74, 61],
       [44, 96, 22, 33, 80]], dtype=int32)

In [77]:
# Any indicando el axis=1 (en las filas)
# Devuelve un booleano de tamaño igual al número de filas.
filas_mayor_que_80 = np.any(file_data > 80, axis=1)
filas_mayor_que_90 = np.any(file_data > 90, axis=1)

file_data[filas_mayor_que_90,:]

array([[42,  9, 52, 60, 28, 98, 25, 83, 40],
       [79, 39,  8, 96, 71, 68, 56, 34, 40],
       [27,  6, 55,  6, 57, 81, 91, 57, 61],
       [69,  0, 63, 35, 15, 44,  7, 46, 93],
       [71, 78, 33, 44, 96, 22, 33, 25, 80]], dtype=int32)

In [82]:
# Filtrar los datos de las filas que tengan valores mayores que 80
f1 = file_data[filas_mayor_que_80,:]
# sobre ese resultado flitrar las columnas que tengan valores mayores que 90
col_mayores_que_90 = np.any(f1 > 90, axis=0)
f1[:,col_mayores_que_90]

array([[66, 42, 88, 72, 50],
       [60, 28, 98, 25, 40],
       [96, 71, 68, 56, 40],
       [ 6, 57, 81, 91, 61],
       [25, 84,  0, 59, 28],
       [35, 15, 44,  7, 93],
       [ 3, 15, 79, 74, 61],
       [44, 96, 22, 33, 80]], dtype=int32)

In [84]:
# Se pueden anidar estas funcioner para acotar un dato por ejemplo
mascara = np.any((file_data > 40) & (file_data < 60), axis=1)
print(mascara)

# Seleccionar los datos que cumplen la condición
file_data[mascara,:]

[ True  True  True  True  True  True False  True]


array([[ 9, 30, 65, 66, 42, 88, 72, 21, 50],
       [42,  9, 52, 60, 28, 98, 25, 83, 40],
       [79, 39,  8, 96, 71, 68, 56, 34, 40],
       [27,  6, 55,  6, 57, 81, 91, 57, 61],
       [51, 35, 81, 25, 84,  0, 59, 65, 28],
       [69,  0, 63, 35, 15, 44,  7, 46, 93],
       [71, 78, 33, 44, 96, 22, 33, 25, 80]], dtype=int32)

In [10]:
# Definimos una matriz en el que cada columna es un mes del año y cada fila es un departamento de mi empresa

departamentos = np.array(['Ventas', 'Marketing', 'RRHH', 'Compras', 'Producción'])

gastos = np.random.randint(0,10000,size=(5,12), dtype=np.int32)
print(gastos)

[[ 692 1332 3939 2403 1537 9703 3230 1827 7335 9914 2255 8383]
 [9033 7459 5510 3715 2547 4048 3410 5403 4232 2287 8208 3168]
 [9018 9467 2804 3897 6952 8537 6818 8704 9085 4429 5487  922]
 [ 238 7284 6619 7143 2953 9804 3235 5776 9878 9109 5921 9908]
 [9683 1024 2137 9421 7787 1682  564 6187 2607 4579 2835 3666]]


In [12]:
# Conocer que departamentos gastan más de 5000€ en el mes de enero
gastos[:,0] > 5000
print(departamentos[gastos[:,0] > 5000])

['Marketing' 'RRHH' 'Producción']
